import type {
  AccentTone,
  Address,
  DemoUser,
  Order,
  OrderItem,
  OrderStatus,
  PaymentMethod,
  Product,
  ProductSpec,
  ProductStatus,
  TrackingStep,
  UserRole,
} from './types'


export const demoUsers: DemoUser[] = [
  {
    id: 'user-helena',
    name: 'Helena Duarte',
    email: 'helena@demoloja.com',
    password: 'Aurora2026!',
    role: 'manager',
    memberSince: '2021',
    city: 'Sao Paulo, SP',
  },
  {
    id: 'user-rafael',
    name: 'Rafael Lemos',
    email: 'rafael@demoloja.com',
    password: 'Compras2026!',
    role: 'customer',
    memberSince: '2023',
    city: 'Curitiba, PR',
  },
]

export const initialProducts: Product[] = [
  {
    id: 'product-tapete-boucle',
    title: 'Tapete Boucle Nuvem',
    category: 'Casa & Decor',
    brand: 'Atelier Bloom',
    description:
      'Tapete macio em textura boucle para salas, quartos e composições com atmosfera editorial.',
    longDescription:
      'Criado para ambientes que pedem aconchego visual e leitura premium, o Tapete Boucle Nuvem combina toque encorpado, tons neutros e acabamento pensado para vitrines elegantes. Funciona muito bem em salas compactas, quartos ou produções fotográficas de produtos.',
    price: 289.9,
    originalPrice: 349.9,
    stock: 11,
    badge: 'Oferta da semana',
    accent: 'peach',
    featured: true,
    sku: 'DO-412',
    sales: 126,
    rating: 4.9,
    reviewCount: 184,
    shipping: 'Frete gratis para Sul e Sudeste',
    installments: 'ou 6x de R$ 48,32 sem juros',
    status: 'Disponivel',
    features: ['Toque macio', 'Base antiderrapante', 'Paleta neutra'],
    specs: [
      { label: 'Medida', value: '1,60 m x 2,00 m' },
      { label: 'Material', value: 'Fibra sintética premium' },
      { label: 'Cor', value: 'Areia clara' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1575414003591-ece8d0416c7a?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'product-difusor-lume',
    title: 'Difusor de Cerâmica Lume',
    category: 'Bem-estar',
    brand: 'demo Home',
    description:
      'Difusor com acabamento fosco e fragrância clean para perfumar ambientes pequenos e médios.',
    longDescription:
      'O Difusor de Cerâmica Lume foi pensado para quem busca perfumar a casa com discrição e sofisticação. O frasco tem desenho minimalista, acompanha varetas de alta absorção e entrega um aroma leve para rotina, home office e espaços de relaxamento.',
    price: 129.9,
    originalPrice: 159.9,
    stock: 18,
    badge: 'Mais procurado',
    accent: 'cyan',
    featured: true,
    sku: 'DO-205',
    sales: 214,
    rating: 4.8,
    reviewCount: 312,
    shipping: 'Entrega rápida para capitais',
    installments: 'ou 4x de R$ 32,47',
    status: 'Disponivel',
    features: ['Frasco reutilizável', 'Aroma clean linen', 'Design fosco'],
    specs: [
      { label: 'Volume', value: '250 ml' },
      { label: 'Duração média', value: '45 dias' },
      { label: 'Ambiente', value: 'Sala, quarto e lavabo' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1602928321679-560bb453f190?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'product-bolsa-siena',
    title: 'Bolsa Everyday Siena',
    category: 'Moda',
    brand: 'Studio Arco',
    description:
      'Bolsa estruturada para uso diário com alça regulável, bolso interno e acabamento minimalista.',
    longDescription:
      'A Bolsa Everyday Siena entrega praticidade e presença visual em um mesmo produto. O formato compacto acomoda itens essenciais, enquanto a paleta atemporal facilita a combinação com looks urbanos, viagens curtas e rotina de trabalho.',
    price: 219.9,
    originalPrice: 259.9,
    stock: 7,
    badge: 'Nova coleção',
    accent: 'berry',
    featured: true,
    sku: 'CV-564',
    sales: 93,
    rating: 4.9,
    reviewCount: 146,
    shipping: 'Envio em até 24 horas',
    installments: 'ou 8x de R$ 27,49',
    status: 'Disponivel',
    features: ['Alça regulável', 'Forro interno', 'Fecho magnético'],
    specs: [
      { label: 'Material', value: 'Couro sintético premium' },
      { label: 'Cor', value: 'Cacau' },
      { label: 'Largura', value: '26 cm' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'product-canecas-sable',
    title: 'Conjunto de Canecas Sable',
    category: 'Casa & Decor',
    brand: 'CasaVitrine Table',
    description:
      'Kit com duas canecas em cerâmica texturizada para cafés especiais, brunches e presentes.',
    longDescription:
      'O conjunto foi desenhado para mesas com identidade visual forte. As canecas possuem alça confortável, acabamento texturizado e cor quente, ideal para destacar kits presenteáveis e composições para conteúdo.',
    price: 118.9,
    originalPrice: 149.9,
    stock: 14,
    badge: 'Escolha da curadoria',
    accent: 'gold',
    featured: false,
    sku: 'CV-318',
    sales: 71,
    rating: 4.7,
    reviewCount: 88,
    shipping: 'Frete econômico disponível',
    installments: 'ou 3x de R$ 39,63',
    status: 'Disponivel',
    features: ['Cerâmica texturizada', 'Kit com 2 unidades', 'Ideal para presente'],
    specs: [
      { label: 'Capacidade', value: '280 ml cada' },
      { label: 'Material', value: 'Cerâmica vitrificada' },
      { label: 'Cor', value: 'Terracota suave' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1517191434949-5e90cd67d2b6?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'product-skincare-terra',
    title: 'Kit Rotina de Skincare Terra',
    category: 'Beleza',
    brand: 'Lumine Skin',
    description:
      'Rotina com espuma de limpeza, sérum e creme leve para quem busca praticidade no autocuidado.',
    longDescription:
      'O Kit Rotina de Skincare Terra concentra três passos essenciais em uma seleção equilibrada para uso diário. A proposta combina texturas leves, fragrância discreta e visual refinado para presentear ou renovar a bancada de cuidados.',
    price: 179.9,
    originalPrice: 219.9,
    stock: 16,
    badge: 'Favorito do mês',
    accent: 'peach',
    featured: false,
    sku: 'CV-677',
    sales: 104,
    rating: 4.8,
    reviewCount: 164,
    shipping: 'Frete grátis acima de R$ 199',
    installments: 'ou 6x de R$ 29,98',
    status: 'Disponivel',
    features: ['Rotina em 3 passos', 'Textura leve', 'Presenteável'],
    specs: [
      { label: 'Conteúdo', value: '3 itens' },
      { label: 'Tipo de pele', value: 'Mista a normal' },
      { label: 'Uso', value: 'Dia e noite' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'product-organizador-frame',
    title: 'Organizador Modular Frame',
    category: 'Utilidades',
    brand: 'Nord Shelf',
    description:
      'Organizador para bancada, escritório ou penteadeira com estrutura modular e desenho limpo.',
    longDescription:
      'Pensado para quem valoriza organização com apelo visual, o Organizador Modular Frame possui divisórias inteligentes e acabamento elegante. Ele se adapta muito bem a home office, cozinha criativa ou composições em loja.',
    price: 89.9,
    originalPrice: 109.9,
    stock: 22,
    badge: 'Praticidade premium',
    accent: 'cyan',
    featured: false,
    sku: 'CV-088',
    sales: 138,
    rating: 4.8,
    reviewCount: 142,
    shipping: 'Envio no mesmo dia útil',
    installments: 'ou 3x de R$ 29,97',
    status: 'Disponivel',
    features: ['Divisórias modulares', 'Estrutura leve', 'Visual minimalista'],
    specs: [
      { label: 'Altura', value: '14 cm' },
      { label: 'Material', value: 'Polímero rígido' },
      { label: 'Cor', value: 'Off-white' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1591129841117-3adfd313e34f?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'product-necessaire-duna',
    title: 'Necessaire Atelier Duna',
    category: 'Presentes',
    brand: 'Studio Arco',
    description:
      'Necessaire estruturada com acabamento leve para kits de viagem, beleza e lembranças especiais.',
    longDescription:
      'Compacta por fora e surpreendente por dentro, a Necessaire Atelier Duna é ideal para montar presentes, compor kits sazonais ou organizar itens de viagem. O acabamento é clean, com zíper suave e toque elegante.',
    price: 79.9,
    originalPrice: 99.9,
    stock: 19,
    badge: 'Leve junto',
    accent: 'berry',
    featured: false,
    sku: 'CV-591',
    sales: 84,
    rating: 4.7,
    reviewCount: 116,
    shipping: 'Frete fixo promocional',
    installments: 'ou 2x de R$ 39,95',
    status: 'Disponivel',
    features: ['Estruturada', 'Leve', 'Ótima para kits'],
    specs: [
      { label: 'Material', value: 'Canvas texturizado' },
      { label: 'Fechamento', value: 'Zíper metálico' },
      { label: 'Cor', value: 'Areia' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1522338140262-f46f591261c8?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'product-luminaria-aura',
    title: 'Luminária de Mesa Aura',
    category: 'Iluminação',
    brand: 'CasaVitrine Home',
    description:
      'Luminária com luz quente, base fosca e desenho contemporâneo para mesa lateral ou escritório.',
    longDescription:
      'A Luminária Aura foi criada para compor ambientes acolhedores com identidade visual forte. A luz quente reforça a atmosfera do ambiente, enquanto a base discreta conversa bem com propostas modernas, naturais ou minimalistas.',
    price: 189.9,
    originalPrice: 229.9,
    stock: 8,
    badge: 'Ambientes acolhedores',
    accent: 'gold',
    featured: false,
    sku: 'CV-744',
    sales: 65,
    rating: 4.9,
    reviewCount: 74,
    shipping: 'Entrega segura com embalagem reforçada',
    installments: 'ou 7x de R$ 27,13',
    status: 'Disponivel',
    features: ['Luz quente', 'Base fosca', 'Ideal para home office'],
    specs: [
      { label: 'Altura', value: '38 cm' },
      { label: 'Voltagem', value: 'Bivolt' },
      { label: 'Cor', value: 'Areia e dourado' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1534073828943-f801091bb18c?auto=format&fit=crop&q=80&w=800',
  },
]

export const initialOrders: Order[] = [
  {
    id: 'PED-5210',
    customerId: 'user-rafael',
    customerName: 'Rafael Lemos',
    createdAt: '2026-04-17T14:35:00.000Z',
    status: 'Em separação',
    channel: 'App',
    paymentLabel: 'Visa final 4821',
    addressLabel: 'Apartamento',
    total: 219.8,
    items: [
      {
        productId: 'product-difusor-lume',
        title: 'Difusor de Ceramica Lume',
        quantity: 1,
        price: 129.9,
      },
      {
        productId: 'product-organizador-frame',
        title: 'Organizador Modular Frame',
        quantity: 1,
        price: 89.9,
      },
    ],
    tracking: [
      {
        label: 'Pagamento confirmado',
        date: '17 abr, 14:35',
        done: true,
      },
      {
        label: 'Pedido em separação',
        date: '17 abr, 16:10',
        done: true,
      },
      {
        label: 'Saiu para transporte',
        date: 'Previsto para hoje',
        done: false,
      },
    ],
  },
  {
    id: 'PED-5188',
    customerId: 'user-rafael',
    customerName: 'Rafael Lemos',
    createdAt: '2026-04-14T09:20:00.000Z',
    status: 'Em transporte',
    channel: 'Site',
    paymentLabel: 'Mastercard final 9210',
    addressLabel: 'Apartamento',
    total: 289.9,
    items: [
      {
        productId: 'product-tapete-boucle',
        title: 'Tapete Boucle Nuvem',
        quantity: 1,
        price: 289.9,
      },
    ],
    tracking: [
      {
        label: 'Pagamento confirmado',
        date: '14 abr, 09:20',
        done: true,
      },
      {
        label: 'Pedido embalado',
        date: '14 abr, 12:40',
        done: true,
      },
      {
        label: 'Em rota para entrega',
        date: '16 abr, 08:15',
        done: true,
      },
    ],
  },
  {
    id: 'PED-5164',
    customerId: 'user-helena',
    customerName: 'Helena Duarte',
    createdAt: '2026-04-11T18:05:00.000Z',
    status: 'Entregue',
    channel: 'Site',
    paymentLabel: 'Amex final 3310',
    addressLabel: 'Casa',
    total: 259.8,
    items: [
      {
        productId: 'product-skincare-terra',
        title: 'Kit Rotina de Skincare Terra',
        quantity: 1,
        price: 179.9,
      },
      {
        productId: 'product-necessaire-duna',
        title: 'Necessaire Atelier Duna',
        quantity: 1,
        price: 79.9,
      },
    ],
    tracking: [
      {
        label: 'Pagamento confirmado',
        date: '11 abr, 18:05',
        done: true,
      },
      {
        label: 'Pedido enviado',
        date: '12 abr, 09:40',
        done: true,
      },
      {
        label: 'Entregue',
        date: '14 abr, 13:20',
        done: true,
      },
    ],
  },
  {
    id: 'PED-5122',
    customerId: 'user-rafael',
    customerName: 'Rafael Lemos',
    createdAt: '2026-04-08T11:15:00.000Z',
    status: 'Entregue',
    channel: 'App',
    paymentLabel: 'Visa final 4821',
    addressLabel: 'Apartamento',
    total: 308.8,
    items: [
      {
        productId: 'product-canecas-sable',
        title: 'Conjunto de Canecas Sable',
        quantity: 1,
        price: 118.9,
      },
      {
        productId: 'product-luminaria-aura',
        title: 'Luminaria de Mesa Aura',
        quantity: 1,
        price: 189.9,
      },
    ],
    tracking: [
      {
        label: 'Pagamento confirmado',
        date: '08 abr, 11:15',
        done: true,
      },
      {
        label: 'Coleta realizada',
        date: '08 abr, 17:30',
        done: true,
      },
      {
        label: 'Entregue',
        date: '10 abr, 14:50',
        done: true,
      },
    ],
  },
]

export const demoPaymentMethods: PaymentMethod[] = [
  {
    id: 'card-helena-01',
    userId: 'user-helena',
    label: 'Cartao principal',
    brand: 'American Express',
    last4: '3310',
    expiry: '08/29',
    holder: 'Helena Duarte',
    primary: true,
  },
  {
    id: 'card-rafael-01',
    userId: 'user-rafael',
    label: 'Cartao principal',
    brand: 'Visa',
    last4: '4821',
    expiry: '10/28',
    holder: 'Rafael Lemos',
    primary: true,
  },
  {
    id: 'card-rafael-02',
    userId: 'user-rafael',
    label: 'Cartao para parcelamento',
    brand: 'Mastercard',
    last4: '9210',
    expiry: '04/30',
    holder: 'Rafael Lemos',
    primary: false,
  },
]

export const demoAddresses: Address[] = [
  {
    id: 'address-helena-01',
    userId: 'user-helena',
    label: 'Casa',
    recipient: 'Helena Duarte',
    street: 'Rua dos Pinheiros, 420',
    city: 'Sao Paulo',
    state: 'SP',
    zipCode: '05422-001',
  },
  {
    id: 'address-rafael-01',
    userId: 'user-rafael',
    label: 'Apartamento',
    recipient: 'Rafael Lemos',
    street: 'Avenida Silva Jardim, 180',
    city: 'Curitiba',
    state: 'PR',
    zipCode: '80240-020',
  },
]
